<?php
/**
 * Plugin Name: Columns DIY
 * Plugin URI: https://github.com/jupiterwise/Columns-DIY/
 * Description: Two simple shortcodes for generating div-based columns and rows. Wrap the desired content in <code>[column]</code> <code>[/column]</code>. Mark the end of a row with <code>[endrow]</code>. CSS not included.
 * Version: 1.0
 * Author: Corey McKrill
 * Author URI: http://jupiterwise.com/
 * License: GNU General Public License v2.0
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 */

if ( ! class_exists( 'Columns_DIY' ) ) {

    class Columns_DIY {
		
		/**
		 * Set the prefix for all generated CSS classes.
		 */
		private $prefix = 'diy-';
		private function pfx( $attr ) { return $this->prefix . $attr; }
		
		/**
		 * Variables for tracking column and row output.
		 */
		private $colcount = '';
		private $rowcount = '';
		private $openrow = '';
		
		/**
		 * Hook into WordPress.
		 */
		function __construct() {
			
			// Shortcodes and filters
			add_shortcode( 'column', array( &$this, 'column_shortcode' ) );
			add_shortcode( 'endrow', array( &$this, 'row_shortcode' ) );
			add_filter( 'the_content', array( &$this, 'cleanup' ), 12, 1 );
			
		}
		
		/**
		 * Wraps content in a column <div>. If it's the first column in the row,
		 * it will also add an opening <div> for the row. The </div> for the row
		 * is generated by the [endrow] shortcode, or automatically after all
		 * other shortcodes have been run.
		 *
		 * Attributes:
		 *
		 * class    - Optional classes for the column <div> element. Separate
		 *            multiple classes with spaces.
		 * rowclass - Optional classes for the row <div> element. Only works
		 *            when included with the first column in a row.
		 */
		function insert_column( $atts, $content = null ) {
			
			global $post;
			$pid = $post->ID;
			$pre_content = '';
			
			// Extract shortcode attributes.
			extract( shortcode_atts( array(
				'class'    => '',
				'rowclass' => ''
			), $atts ) );
			
			// If it's the first column in the row, add an opening <div>.
			if ( ! $this->openrow )
				$pre_content .= $this->begin_row( $rowclass );
			
			// Increment the column count.
			if ( isset( $this->colcount[$pid] ) ) {
				$this->colcount[$pid]++;
			} else {
				$this->colcount[$pid] = 1;
			}
			
			// Build the initial list of classes to add to column <div>.
			$colclasslist = $this->pfx( 'column' ) . ' ' . $this->pfx( 'column' ) . '-' . $this->colcount[$pid];
			
			// Add custom classes.
			if ( $class )
				$colclasslist .= ' ' . esc_attr( $class );
			
			// Put it all together.
			$content = $pre_content . '<div class="' . $colclasslist . "\">\n<p>" . $content . "</p>\n</div><!-- end " . $this->pfx( 'column' ) . " -->\n";
			
			// Allow for other shortcodes inside [column][/column].
			do_shortcode( $content );
			
			// Output
			return $content;
			
		}
		
		/**
		 * Generate the opening <div> for a row. To add custom classes to this
		 * <div>, use the rowclass attribute in the first [column] of a row.
		 */
		function begin_row( $rowclass = null ) {
			
			global $post;
			$pid = $post->ID;
			
			// Increment the row count.
			if ( isset( $this->rowcount[$pid] ) ) {
				$this->rowcount[$pid]++;
			} else {
				$this->rowcount[$pid] = 1;
			}
			
			// Build the initial list of classes to add to row <div>.
			$rowclasslist = $this->pfx( 'row' ) . ' ' . $this->pfx( 'row' ) . '-' . $this->rowcount[$pid];
			
			// Add custom classes.
			if ( $rowclass )
				$rowclasslist .= ' ' . esc_attr( $rowclass );
			
			// Mark the row as "open" (no closing <div> yet).
			$this->openrow = 1;
			
			// Send opening <div> to insert_column.
			return '<div class="' . $rowclasslist . "\">\n";
		
		}
		
		/**
		 * Close the row <div>.
		 */
		function end_row() {
			
			global $post;
			$pid = $post->ID;
			
			// Mark the row as "closed".
			$this->openrow = 0;
			
			// Reset column count.
			$this->colcount[$pid] = 0;
			
			// Send the closing </div> to the compiling function.
			return "</div><!-- end " . $this->pfx( 'row' ) . " -->\n\n";
		
		}
		
		/**
		 * Close the last row <div> if it's still open. Clean up messy HTML left
		 * in the content as a result of the inline nature of shortcodes.
		 */
		function cleanup( $content ) {
			
			// Tack on the closing </div>
			if ( $this->openrow )
				$content .= $this->end_row();
			
			// Regex patterns for cleaning up the HTML.
			$patterns = array(
				array( '/\n?<p><div class="' . $this->pfx( 'column' ) . '/', '<div class="' . $this->pfx( 'column' ) ),
				array( '/<\/p>\n?<div class="' . $this->pfx( 'row' ) . '/', '<div class="' . $this->pfx( 'row' ) ),
				array( '/end ' . $this->pfx( 'row' ) . ' -->\n?<\/p>/', "end " . $this->pfx( 'row' ) . " -->\n" )
			);
			
			// Run the regex.
			foreach ( $patterns as $pattern ) {
				$content = preg_replace( $pattern[0], $pattern[1], $content );
			}
			
			// Send the cleaned up content on its way.
			return $content;
		
		}
		
		/**
		 * In case the shortcode should ever trigger more than one (unrelated)
		 * function. Kind of redundant at the moment.
		 */
		function column_shortcode( $atts, $content ) {
			return $this->insert_column( $atts, $content );
		}
		
		/**
		 * Ditto.
		 */
		function row_shortcode() {
			return $this->end_row();
		}
		
	} // End class Columns_DIY
	
	// Instantiate the plugin.
	$columns_diy = new Columns_DIY();
	
} // End if